# Dependencies
markdown:         kramdown
#redcarpet:
#  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      rouge

# Permalinks
permalink:        /posts/:title/

paginate_path: "/blog/page:num/"

# User Configuration
title:            'Piano 3D'
tagline:          'a piano app for IPhone and Android'
url:              https://piano3d.com
baseurl:          '/'
paginate:         5
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

# Version Info
version:          0.0.5

author:
  name: 'Alex Sikilinda'
  email: 'alex.sikilinda@gmail.com'